Repository asyncapi/community, pull requests merged in 2023-02, with the labels that each got.

#576 chore: add Daniel Kocot to Ambassadors Program.
  AMBASSADORS_MEMBERS.json
Labels: ready-to-merge, autoupdate

#572 chore: ambassador program document update
  AMBASSADOR_ORGANIZATION.md
Labels: ready-to-merge

#582 docs: add documentation for supporting AsyncAPI
  PROJECT_FINANCE.md
Labels: ready-to-merge

#574 chore(tsc): add @LouisXhaferi to TSC list
  TSC_MEMBERS.json
Labels: ready-to-merge

#592 docs: contributing instructions added
  contribute-blog-post.md
Labels: ready-to-merge, 📑 docs, area/docs

#595 chore: add ldussart to the ambassafor program
  AMBASSADORS_MEMBERS.json
Labels: ready-to-merge

#600 docs: correct filenames for manual and automated tools
  new-tool-documentation.md
Labels: ready-to-merge

#613 chore: add governance file
  GOVERNANCE.md
Labels: ready-to-merge
