Repository asyncapi/community, pull requests merged in 2024-01, with the labels that each got.

#960 docs: add first elements of the onboarding guide.
  docs/onboarding-guide/_section.md
  docs/onboarding-guide/docs-onboarding-checklist.md
  docs/onboarding-guide/index.md
  docs/onboarding-guide/prerequisite-knowledge.md
  docs/onboarding-guide/technical-writer-contributor-responsibilities.md
Labels: ready-to-merge

#959 docs: add docs community section to onboarding guide
  docs/onboarding-guide/docs-community.md
Labels: ready-to-merge, 📑 docs, area/docs

#1021 docs: remove my name from docs onboarding guide
  docs/onboarding-guide/docs-onboarding-checklist.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#1025 ci: checkout of PR branch is not working
  .github/workflows/maintainers-tsc-changes-verification.yaml
Labels: ready-to-merge

#1026 chore(tsc): add Ashish Padhy as a new TSC member
  MAINTAINERS.yaml
Labels: ready-to-merge

#1029 chore(ambassador): update ldussart contributions for 2023
  AMBASSADORS_MEMBERS.json
Labels: ready-to-merge

#993 chore(tsc): add Ashmit JaiSarita Gupta as new TSC member
  MAINTAINERS.yaml
Labels: ready-to-merge

#1022 chore(tsc): add Samir AMZANI as a new TSC member
  MAINTAINERS.yaml
Labels: ready-to-merge
