Repository asyncapi/community, pull requests merged in 2025-05, with the labels that each got.

#1634 chore: introduce governance board
  .gitvote.yml
  CHARTER.md
  GOVERNANCE.md
  voting.md
Labels: ready-to-merge, vote, gitvote

#1883 docs: add missing curly braces
  docs/styleguide/grammar.md
Labels: ready-to-merge

#1888 docs: update format of AMBASSADORS_MEMBERS.json
  AMBASSADORS_MEMBERS.json
  AMBASSADOR_ORGANIZATION.md
Labels: ready-to-merge, bounty

#1889 chore: add Daniel to TSC
  AMBASSADORS_MEMBERS.json
Labels: ready-to-merge

#1896 chore: update meeting workflow file
  .github/workflows/create-event-ad-hoc.yml
Labels: ready-to-merge

#1725 docs: add onboarding code contributor guide
  docs/onboarding-guide/code-contributor-guide.md
Labels: ready-to-merge

#1899 feat: update forHire status and company
  MAINTAINERS.yaml
Labels: ready-to-merge

#1900 chore: add Naresh Jain as an ambassador
  AMBASSADORS_MEMBERS.json
Labels: ready-to-merge

#1730 docs: expand community docs: contributor - simple contribution flow a…
  docs/onboarding-guide/contribution-flow.md
Labels: ready-to-merge

#1770 docs: remove the sponsors and update the READme
  README.md
Labels: ready-to-merge

#1907 chore: add Naresh to TSC
  AMBASSADORS_MEMBERS.json
Labels: ready-to-merge
